In [1]:
import numpy as np
import time 

In [2]:
a = np.array([1,2,3,4,5])
a = np.random.rand(1000000)
print(a)

[0.08013168 0.98292325 0.64792349 ... 0.28367247 0.43437065 0.6607147 ]


In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print('vectorised version ' + str(1000*(toc-tic)) + 'ms')

vectorised version 2.9573440551757812ms


# Broadcasting

In [6]:
# if add subtract multiply divide m*n matrix, python will convert 1*n and m*1 to m*n matrix
a = np.array([[1,2],[3,4]])  # m*n ; 2x2
b = np.array([[5,5]])        # 1*n 
c = np.array([[5],[5]])      # m*1
print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[5 5]]
[[5]
 [5]]


In [11]:
print(a+b)
print(a+c)
print(a*b)
print(a/b)

[[6 7]
 [8 9]]
[[6 7]
 [8 9]]
[[ 5 10]
 [15 20]]
[[0.2 0.4]
 [0.6 0.8]]


In [17]:
d = np.dot(a,a)              # 'normal' matrix multiplication 
print(d)

[[ 7 10]
 [15 22]]


# Tips

In [15]:
# Do not use
a = np.random.randn(5,)
# Do use
b = np.random.randn(5,1)
c = np.random.randn(1,5)
assert(b.shape == (5,1))
# Can use reshape to fix first example
a1 = a.reshape((5,1))
print(a)
print(a1)

[-1.00473433  0.20717425 -0.56486599  0.98767093  0.32380152]
[[-1.00473433]
 [ 0.20717425]
 [-0.56486599]
 [ 0.98767093]
 [ 0.32380152]]
