In [15]:
import datetime as datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
np.set_printoptions(threshold = 10000)
print(tf.__version__)

1.9.0


# Wk1 DNN Course 1 - Part 2 - Lesson 2 - Notebook

In [16]:
# y = 2x - 1
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error') #sgd stochastic gradient descent
model.fit(xs, ys, epochs=500)

Epoch 1/500
6/6 [==============================] - 0s 19ms/step - loss: 23.6210
Epoch 2/500
6/6 [==============================] - 0s 159us/step - loss: 18.8677
Epoch 3/500
6/6 [==============================] - 0s 166us/step - loss: 15.1223
Epoch 4/500
6/6 [==============================] - 0s 166us/step - loss: 12.1698
Epoch 5/500
6/6 [==============================] - 0s 332us/step - loss: 9.8413
Epoch 6/500
6/6 [==============================] - 0s 166us/step - loss: 8.0039
Epoch 7/500
6/6 [==============================] - 0s 166us/step - loss: 6.5530
Epoch 8/500
6/6 [==============================] - 0s 166us/step - loss: 5.4062
Epoch 9/500
6/6 [==============================] - 0s 161us/step - loss: 4.4988
Epoch 10/500
6/6 [==============================] - 0s 167us/step - loss: 3.7799
Epoch 11/500
6/6 [==============================] - 0s 166us/step - loss: 3.2094
Epoch 12/500
6/6 [==============================] - 0s 166us/step - loss: 2.7556
Epoch 13/500
6/6 [================

Epoch 103/500
6/6 [==============================] - 0s 332us/step - loss: 0.1774
Epoch 104/500
6/6 [==============================] - 0s 333us/step - loss: 0.1737
Epoch 105/500
6/6 [==============================] - 0s 166us/step - loss: 0.1701
Epoch 106/500
6/6 [==============================] - 0s 166us/step - loss: 0.1666
Epoch 107/500
6/6 [==============================] - 0s 166us/step - loss: 0.1632
Epoch 108/500
6/6 [==============================] - 0s 333us/step - loss: 0.1599
Epoch 109/500
6/6 [==============================] - 0s 334us/step - loss: 0.1566
Epoch 110/500
6/6 [==============================] - 0s 166us/step - loss: 0.1534
Epoch 111/500
6/6 [==============================] - 0s 166us/step - loss: 0.1502
Epoch 112/500
6/6 [==============================] - 0s 166us/step - loss: 0.1471
Epoch 113/500
6/6 [==============================] - 0s 167us/step - loss: 0.1441
Epoch 114/500
6/6 [==============================] - 0s 332us/step - loss: 0.1412
Epoch 115/500
6/

Epoch 203/500
6/6 [==============================] - 0s 166us/step - loss: 0.0223
Epoch 204/500
6/6 [==============================] - 0s 166us/step - loss: 0.0218
Epoch 205/500
6/6 [==============================] - 0s 333us/step - loss: 0.0214
Epoch 206/500
6/6 [==============================] - 0s 333us/step - loss: 0.0209
Epoch 207/500
6/6 [==============================] - 0s 332us/step - loss: 0.0205
Epoch 208/500
6/6 [==============================] - 0s 161us/step - loss: 0.0201
Epoch 209/500
6/6 [==============================] - 0s 332us/step - loss: 0.0197
Epoch 210/500
6/6 [==============================] - 0s 332us/step - loss: 0.0192
Epoch 211/500
6/6 [==============================] - 0s 166us/step - loss: 0.0189
Epoch 212/500
6/6 [==============================] - 0s 334us/step - loss: 0.0185
Epoch 213/500
6/6 [==============================] - 0s 166us/step - loss: 0.0181
Epoch 214/500
6/6 [==============================] - 0s 333us/step - loss: 0.0177
Epoch 215/500
6/

Epoch 303/500
6/6 [==============================] - 0s 333us/step - loss: 0.0028
Epoch 304/500
6/6 [==============================] - 0s 166us/step - loss: 0.0027
Epoch 305/500
6/6 [==============================] - 0s 166us/step - loss: 0.0027
Epoch 306/500
6/6 [==============================] - 0s 166us/step - loss: 0.0026
Epoch 307/500
6/6 [==============================] - 0s 166us/step - loss: 0.0026
Epoch 308/500
6/6 [==============================] - 0s 332us/step - loss: 0.0025
Epoch 309/500
6/6 [==============================] - 0s 166us/step - loss: 0.0025
Epoch 310/500
6/6 [==============================] - 0s 167us/step - loss: 0.0024
Epoch 311/500
6/6 [==============================] - 0s 0us/step - loss: 0.0024
Epoch 312/500
6/6 [==============================] - 0s 166us/step - loss: 0.0023
Epoch 313/500
6/6 [==============================] - 0s 332us/step - loss: 0.0023
Epoch 314/500
6/6 [==============================] - 0s 333us/step - loss: 0.0022
Epoch 315/500
6/6 

Epoch 401/500
6/6 [==============================] - 0s 166us/step - loss: 3.6542e-04
Epoch 402/500
6/6 [==============================] - 0s 166us/step - loss: 3.5792e-04
Epoch 403/500
6/6 [==============================] - 0s 332us/step - loss: 3.5056e-04
Epoch 404/500
6/6 [==============================] - 0s 165us/step - loss: 3.4336e-04
Epoch 405/500
6/6 [==============================] - 0s 166us/step - loss: 3.3631e-04
Epoch 406/500
6/6 [==============================] - 0s 166us/step - loss: 3.2940e-04
Epoch 407/500
6/6 [==============================] - 0s 166us/step - loss: 3.2264e-04
Epoch 408/500
6/6 [==============================] - 0s 334us/step - loss: 3.1601e-04
Epoch 409/500
6/6 [==============================] - 0s 162us/step - loss: 3.0951e-04
Epoch 410/500
6/6 [==============================] - 0s 166us/step - loss: 3.0316e-04
Epoch 411/500
6/6 [==============================] - 0s 166us/step - loss: 2.9693e-04
Epoch 412/500
6/6 [==============================] - 0

Epoch 497/500
6/6 [==============================] - 0s 160us/step - loss: 4.9829e-05
Epoch 498/500
6/6 [==============================] - 0s 166us/step - loss: 4.8805e-05
Epoch 499/500
6/6 [==============================] - 0s 166us/step - loss: 4.7803e-05
Epoch 500/500
6/6 [==============================] - 0s 166us/step - loss: 4.6820e-05


In [3]:
print(model.predict([10.0]))

[[18.986164]]


# Wk2 DNN Course 1 - Part 4 - Lesson 2 - Notebook

Sequential: That defines a SEQUENCE of layers in the neural network

Flatten: Remember earlier where our images were a square, when you printed them out? Flatten just takes that square and turns it into a 1 dimensional set.

Dense: Adds a layer of neurons

Each layer of neurons need an activation function to tell them what to do. There's lots of options, but just use these for now.

Relu effectively means "If X>0 return X, else return 0" -- so what it does it it only passes values 0 or greater to the next layer in the network.

Softmax takes a set of values, and effectively picks the biggest one, so, for example, if the output of the last layer looks like [0.1, 0.1, 0.05, 0.1, 9.5, 0.1, 0.05, 0.05, 0.05], it saves you from fishing through it looking for the biggest value, and turns it into [0,0,0,0,1,0,0,0,0] -- The goal is to save a lot of coding!

Last layer has 10 neurons because there are 10 labels!

In [8]:
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
#plt.imshow(training_images[0]) #image
#print(training_labels[0]) #9
#print(training_images[0]) #matrixes
training_images  = training_images / 255.0  #normalise
test_images = test_images / 255.0           #normalise

In [9]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.20):
      print("\nReached 60% accuracy so cancelling training!")
      self.model.stop_training = True
callbacks = myCallback()

In [10]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),                            #flatten to same dimensions
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),    #increase for better accuracy
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)]) #10 labels so 10
#1 hidden layer is enough for simple problem

In [11]:
model.compile(optimizer = tf.train.AdamOptimizer(),
              #optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(training_images, training_labels, epochs=200, callbacks=[callbacks])

Epoch 1/200
60000/60000 [==============================] - 3s 58us/step - loss: 0.5027 - acc: 0.8238
Epoch 2/200
60000/60000 [==============================] - 3s 53us/step - loss: 0.3755 - acc: 0.8644
Epoch 3/200
60000/60000 [==============================] - 3s 53us/step - loss: 0.3358 - acc: 0.8764
Epoch 4/200
60000/60000 [==============================] - 3s 50us/step - loss: 0.3125 - acc: 0.8871
Epoch 5/200
60000/60000 [==============================] - 3s 46us/step - loss: 0.2941 - acc: 0.8912
Epoch 6/200
60000/60000 [==============================] - 3s 49us/step - loss: 0.2806 - acc: 0.8964
Epoch 7/200
60000/60000 [==============================] - 3s 46us/step - loss: 0.2671 - acc: 0.9006
Epoch 8/200
60000/60000 [==============================] - 3s 48us/step - loss: 0.2563 - acc: 0.9054
Epoch 9/200
60000/60000 [==============================] - 3s 55us/step - loss: 0.2470 - acc: 0.9076
Epoch 10/200
60000/60000 [==============================] - 3s 53us/step - loss: 0.2380 - a

In [13]:
model.evaluate(test_images, test_labels)  #output time and acc

10000/10000 [==============================] - 0s 42us/step


[0.35432593443393706, 0.8812]

In [14]:
classifications = model.predict(test_images) 
print(classifications[[0,1,2,3]])      #probabilities for each of the 10 labels; the highest is chosen
print(test_labels[[0,1,2,3]])          #position [1] has the highest probablity of 1.00 !

[[5.51942769e-10 5.74028214e-10 1.19255855e-10 2.07194681e-13
  8.57707949e-09 6.37127727e-04 1.24544715e-11 4.32804320e-03
  8.98717992e-12 9.95034814e-01]
 [1.14366030e-05 6.39105586e-15 9.96294320e-01 3.17002563e-10
  3.35447141e-03 1.56206974e-11 3.39834631e-04 5.42519141e-10
  6.45752722e-12 3.95424741e-13]
 [9.93572152e-12 1.00000000e+00 1.41594068e-14 1.92135110e-11
  1.33855579e-12 1.79888651e-26 5.85194260e-14 1.37584294e-27
  1.07192756e-14 2.55722604e-22]
 [8.92327531e-12 1.00000000e+00 1.16030029e-13 9.84806015e-09
  1.94018496e-10 1.55501518e-17 5.98910435e-11 2.49004528e-21
  2.72757975e-14 6.87697333e-19]]
[9 2 1 1]


# Wk3 CNN Course 1 - Part 6 - Lesson 2 - Notebook

Convolution: 
Multiply each pixel by 3x3 filter, border pixel not used, 28x28 reduced to 26x26, make features clearer

Pooling:
Take max out of 2x2, 16x16 reduced to 4x4, 64 filters, 1 grey scale byte

In [4]:
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images=training_images.reshape(60000, 28, 28, 1)                          # 60,000 28x28x1 items in a list
training_images=training_images / 255.0                                            # to single 4D list that is 60,000x28x28x1
test_images=test_images.reshape(10000, 28, 28, 1)
test_images=test_images/255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(28, 28, 1)),   #64 filters, 3x3 filter, 1 greyscale byte
  tf.keras.layers.MaxPooling2D(2, 2),                                              #reduce 2x2 to 1
  tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),                                #5*5*64 = 1600; 128 can be varied
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()
model.fit(training_images, training_labels, epochs=5)
test_loss = model.evaluate(test_images, test_labels)
test_loss

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 64)        640       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 11, 11, 64)        36928     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               204928    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total para

In [23]:
import numpy as np
a1 = np.arange(8)
a2 = np.arange(8).reshape(4,2)
a3 = np.arange(8).reshape(1,8)
a4 = np.arange(10).reshape(10)
print(a1)
print(a2)
print(a3)
print(a4)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3 4 5 6 7]]
[0 1 2 3 4 5 6 7 8 9]


# Wk4 